### ISSUE TITLE
only one json file

### ISSUE THREAD

**Issue by eejlny** [meyerjo/deepdrive_dataset_tfrecord#3]
when running the command I am getting the following error:

Traceback (most recent call last):
  File "create_tfrecord.py", line 51, in <module>
    daytime_type=FLAGS.daytime, classes=FLAGS.classes
  File "/hdd1/eejlny/projects/tensorflow/coral_models/models/research/deepdrive_dataset_tfrecord/deepdrive_dataset/deepdrive_dataset_writer.py", line 421, in write_tfrecord
    picture_id, full_labels_path=full_labels_path)
  File "/hdd1/eejlny/projects/tensorflow/coral_models/models/research/deepdrive_dataset_tfrecord/deepdrive_dataset/deepdrive_dataset_writer.py", line 270, in get_annotation
    full_labels_path, picture_id + '.json'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/eejlny/.deepdrive/labels/bdd100k/labels/100k/565d82d9-0d7b69c3.json'

I do not have a json file per picture but only one json file so not sure how to fix, please ?

**Comment by meyerjo** [comment]
I have to check it again, but the code should be able to also work with one json file. Maybe you can check the options. I will have a look at it on the weekend

**Comment by eejlny** [comment]
Thanks for the reply.

I do not see any options about this. I can see that there is some code about using one json file but I do not know how to ask the script to use this. I just downloaded the two files from the BDD web and follow the instructions.  Maybe it is something with new format or old format but I do not know how to control it.

**Comment by eejlny** [comment]
If I force new_format to one as shown below then it does not crash but the tfrecord is empty with zero bytes. Do I need to do something else than:

 python3 create_tfrecord.py

  # get the annotations for the given file
                new_format = 1
                if not new_format:
                    picture_id_annotations = DeepdriveDatasetWriter.get_annotation(
                        picture_id, full_labels_path=full_labels_path)
                else:
                    picture_id_annotations = obj_annotation_dict.get(picture_id, None)

**Comment by meyerjo** [comment]
Ok I will check on the weekend

**Comment by eejlny** [comment]
OK, it looks like there are some discrepancies of where the data is stored and where the script is expecting to find it. I managed to get the records by moving data around.

**Comment by CTcome-Tamu** [comment]
> OK, it looks like there are some discrepancies of where the data is stored and where the script is expecting to find it. I managed to get the records by moving data around.

Hello, can you tell what means that 'by moving the data around'? I met the same problem too... 

Thanks so much for you help!

**Comment by ECEMACHINE** [comment]
Hi, 
I met the problem too...
Is there any solution yet?

Thanks

**Comment by ECEMACHINE** [comment]
> OK, it looks like there are some discrepancies of where the data is stored and where the script is expecting to find it. I managed to get the records by moving data around.

Yes, seems the tfrecords location was not be got correctly
